# Generated by Django 4.2.4 on 2023-08-24 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
        migrations.RenameField(
            model_name='peliculas',
            old_name='Genero',
            new_name='genero',
        ),
        migrations.RenameField(
            model_name='peliculas',
            old_name='Titulo',
            new_name='titulo',
        ),
        migrations.RenameField(
            model_name='series',
            old_name='Genero',
            new_name='genero',
        ),
        migrations.RenameField(
            model_name='series',
            old_name='Temporadas',
            new_name='temporadas',
        ),
        migrations.RenameField(
            model_name='series',
            old_name='Titulo',
            new_name='titulo',
        ),
        migrations.RemoveField(
            model_name='peliculas',
            name='duracion',
        ),
        migrations.AddField(
            model_name='peliculas',
            name='contenido',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='peliculas',
            name='cover',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='peliculas',
            name='director',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppCoder.directores'),
        ),
        migrations.AddField(
            model_name='peliculas',
            name='imagen',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='peliculas',
            name='overview',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='peliculas',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.RemoveField(
            model_name='directores',
            name='filmografia',
        ),
        migrations.AddField(
            model_name='directores',
            name='filmografia',
            field=models.ManyToManyField(to='AppCoder.peliculas'),
        ),
    ]
