# Generated by Django 4.2.4 on 2023-08-25 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0004_rename_contenido_peliculas_reseña_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='peliculas',
            name='destacada',
            field=models.BooleanField(default=False),
        ),
    ]
