# Generated by Django 4.2.4 on 2023-08-29 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0006_directores_biografia_directores_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='autor_reseña',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppCoder.curadores'),
        ),
        migrations.AddField(
            model_name='series',
            name='cover',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='series',
            name='destacada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='series',
            name='imagen',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='series',
            name='overview',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='series',
            name='reseña',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='series',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.RemoveField(
            model_name='series',
            name='genero',
        ),
        migrations.AddField(
            model_name='series',
            name='genero',
            field=models.ManyToManyField(to='AppCoder.generos'),
        ),
    ]
