# Generated by Django 4.2.4 on 2023-08-29 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0007_series_autor_reseña_series_cover_series_destacada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='directores',
            name='citas',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
