# Generated by Django 4.2.4 on 2023-08-29 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0008_directores_citas'),
    ]

    operations = [
        migrations.AddField(
            model_name='directores',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
