# Generated by Django 4.2.4 on 2023-08-29 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0009_directores_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curadores',
            old_name='apeliido',
            new_name='apellido',
        ),
        migrations.RenameField(
            model_name='directores',
            old_name='apeliido',
            new_name='apellido',
        ),
    ]
