# Generated by Django 4.2.4 on 2023-08-29 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0010_rename_apeliido_curadores_apellido_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='directores',
            old_name='img',
            new_name='imagen',
        ),
    ]
