# Generated by Django 4.2.4 on 2023-08-30 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0011_rename_img_directores_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directores',
            name='citas',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
