# Generated by Django 4.2.4 on 2023-08-30 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0012_alter_directores_citas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peliculas',
            name='año',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='peliculas',
            name='titulo',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
