# Generated by Django 4.2.4 on 2023-08-30 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0013_alter_peliculas_año_alter_peliculas_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peliculas',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
