# Generated by Django 4.2.5 on 2023-09-05 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0016_remove_peliculas_overview_remove_series_overview'),
    ]

    operations = [
        migrations.AddField(
            model_name='peliculas',
            name='overview',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='series',
            name='overview',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='peliculas',
            name='titulo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='series',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
