# Generated by Django 4.2.5 on 2023-09-05 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0017_peliculas_overview_series_overview_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peliculas',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
