# Generated by Django 4.2.5 on 2023-09-05 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0020_alter_peliculas_fecha_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generos',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='fecha_creacion',
            field=models.DateField(auto_now_add=True),
        ),
    ]
