# Generated by Django 4.2.5 on 2023-09-05 18:43

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0021_alter_generos_slug_alter_series_fecha_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='peliculas',
            name='video_link',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True),
        ),
    ]
