# Generated by Django 4.2.5 on 2023-09-15 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0024_alter_peliculas_autor_reseña_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peliculas',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
