# Generated by Django 4.2.4 on 2023-09-16 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0026_alter_peliculas_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='año',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='temporadas',
            field=models.IntegerField(null=True),
        ),
    ]
