# Generated by Django 4.2.4 on 2023-09-23 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0032_alter_peliculas_autor_reseña'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='link',
            new_name='redes',
        ),
        migrations.AddField(
            model_name='perfil',
            name='ciudad',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='fecha_nac',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='pais',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='web',
            field=models.URLField(blank=True, null=True),
        ),
    ]
