# Generated by Django 4.2.4 on 2023-09-25 02:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AppCoder', '0033_rename_link_perfil_redes_perfil_ciudad_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField(help_text='Ingrese un comentario', max_length=1000)),
                ('fecha_comentario', models.DateField(auto_now_add=True)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('peliculas', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppCoder.peliculas')),
                ('series', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppCoder.series')),
            ],
            options={
                'ordering': ['-fecha_comentario'],
            },
        ),
    ]
