# Generated by Django 4.2.4 on 2023-09-25 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0035_alter_comentarios_fecha_comentario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generos',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
