# Generated by Django 4.2.4 on 2023-09-25 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0036_alter_generos_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generos',
            name='slug',
            field=models.SlugField(allow_unicode=True, null=True, unique=True),
        ),
    ]
