# Generated by Django 4.2.5 on 2023-09-28 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0038_alter_generos_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Curadores',
        ),
    ]
